services:
  postgres:
    container_name: postgres-devsphere
    image: postgres
    environment:
      POSTGRES_USER: maicon
      POSTGRES_PASSWORD: qwerty50
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  test-db:
    container_name: postgres-devsphere-test
    image: postgres
    environment:
      POSTGRES_USER: test_maicon
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: your_test_db
    ports:
      - "5433:5432"

  pgadmin:
    container_name: pgadmin_container-devsphere
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: